package com.example.navegacioncifradopsp.common

object Constantes {
    const val USUARIO_GUARDADO = "Usuario guardado correctamente"
    const val USUARIO_ACTUALIZADO = "Usuario actualizado correctamente"
    const val USUARIO_ELIMINADO = "Usuario eliminado correctamente"

    const val CREW = "crew"
    const val ID = "id"
    const val KNOW_DEPARTMENT = "known_for_department"
    const val  DEPARTMENT = "department"
    const val ORIGINAL_NAME = "original_name"
    const val NAME = "name"
    const val GENRES = "genres"
    const val PAGE = "page"
    const val ORIGINAL_TITLE = "original_title"
    const val POSTER_PATH = "poster_path"
    const val RELEASE_DATE = "release_date"
    const val VOTE = "vote_average"
    const val GENRE_IDS = "genre_ids"
    const val URLPATH_POSTER = "https://image.tmdb.org/t/p/w500"
    const val EMAIL = "email"
    const val USERNAME = "username"
    const val PRODUCCIONES = "producciones"
    const val USUARIOS = "usuarios"
    const val RESULTS = "results"
    const val DIRECTING = "Directing"
    const val DESCONOCIDO = "Desconocido"
    const val NO_SE_HA_ENCONTRADO = "No se ha encontrado la produccion"
    const val ERROR_ = "Error "
    const val ERROR_ACTUALIZAR = "Error al actualizar el usuario"
    const val ERROR_BORRAR = "Error al eliminar el usuario"
    const val ERROR_GUARDAR = "Error al guardar el usuario"
    const val PAGINA_NEGATIVA = "La pagina no puede ser negativa ni mayor de 500"
    const val ID_NEGATIVO = "El id no puede ser negativo"
    const val CAMPOS_VACIOS = "No puede haber campos vacios"
    const val API_KEY = "api_key"
    const val SEPARACION_POR_COMA = ", "

    const val PRODUCCION_GUARDADA = "Producción añadida"
    const val PRODUCCION_ELIMINADA = "Producción borrada"
    const val PRODUCCION_ACTUALIZADA = "Producción actualizada"


    const val NOMBRE_OBLIGATORIO = "El nombre es obligatorio"
    const val DIRECTOR_OBLIGATORIO = "El director es obligatorio"
    const val ERROR = "ERROR"
    const val TITULO_PANTALLA = "Añadir pelicula"
    const val NOMBRE = "Nombre"
    const val TIPO = "Tipo:"
    const val PELICULA = "Pelicula"
    const val SERIE = "Serie"
    const val DIRECTOR = "Director"
    const val LANZAMIENTO = "Lanzamiento"
    const val N_SEASONS = "Nº de seasons"
    const val GENERO = "Lanzamiento"
    const val PAIS = "Pais"
    const val VALORACION = "Valoracion"
    const val COMEDIA = "Comedia"
    const val DRAMA = "Drama"
    const val FICCION = "Ficción / Fantasia"
    const val TERROR = "Terror"
    const val ESTADOS_UNIDOS = "Estados Unidos"
    const val CHINA = "China"
    const val JAPON = "Japón"
    const val REINO_UNIDO = "Reino Unido"
    const val FRANCIA = "Francia"
    const val ESPANIA = "España"
    const val LIMPIAR = "Limpiar"
    const val BORRAR = "Borrar"
    const val GUARDAR = "Guardar"
    const val ACTUALIZAR = "Actualizar"
    const val ANTERIOR = "Anterior"
    const val SIGUIENTE = "Siguiente"
    const val ELEGIR = "Elegir"
    const val CERO = '0'
}